services:
  my-nginx-service:
    image: nginx

  web:
    image: thinhduckhoi/rk8s-py:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "thinhduckhoi/rk8s-py:${TAG:-latest}"
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - mywebdata:/app/data

  my-redis-service:
    image: redis
    volumes: 
      - myredisdata:/data    

volumes:
  mywebdata:
  myredisdata:
